AceAdmin/Areas/Admin/Models/CategoriesViewModel.cs
using AceModel.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AceAdmin.Areas.Admin.Models
{
    public class CategoriesViewModel
    {
        public Category categoryInfo { get; set; }
        public bool isMenu { get; set; }
        public Category parentCategory { get; set; }

    }
}

AceAdmin/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AceAdmin.Areas.Admin.Models;
using AceAdmin.Common;
using AceModel.Entity;

namespace AceAdmin.Areas.Admin.Controllers
{
    public class CategoriesController : Controller
    {
        private AceAdminEntities db = new AceAdminEntities();

        // GET: Categories
        public ActionResult Index()
        {
            var lstData = db.Categories.ToList();
            var lstNew = new List<CategoriesViewModel>();
            foreach (Category cate in lstData)
            {
                var cateViewModel = new CategoriesViewModel();
                cateViewModel.categoryInfo = cate;
                cateViewModel.parentCategory = db.Categories.Find(cate.ParentId);
                if (cate.Type == 1)
                {
                    cateViewModel.isMenu = true;
                }
                else
                {
                    cateViewModel.isMenu = false;
                }
                lstNew.Add(cateViewModel);
            }
            return View(lstNew);
        }
        [ChildActionOnly]
        public Category getCategory(int cateId)
        {
            Category category = db.Categories.Find(cateId);
            return category;
        }
        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            ViewBag.Status = Utitlitys.StatusToList();
            ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "Name");
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoriesViewModel category)
        {
            if (ModelState.IsValid)
            {
                category.categoryInfo.CreateAt = DateTime.Now;
                category.categoryInfo.CreateBy = User.Identity.Name;
                if (category.isMenu == true)
                {
                    category.categoryInfo.Type = 1;
                }
                else
                {
                    category.categoryInfo.Type = 0;
                }
                db.Categories.Add(category.categoryInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //   ViewBag.ParentId = new SelectList(db.Category.ToList(), "Id", "Name",category.ParentId);
            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.Status = Utitlitys.StatusToList();
            ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "Name");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            CategoriesViewModel viewModel = new CategoriesViewModel();
            viewModel.categoryInfo = category;
            if (viewModel.isMenu == true)
            {
                viewModel.categoryInfo.Type = 1;
            }
            else
            {
                viewModel.categoryInfo.Type = 0;
            }

            return View(viewModel);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoriesViewModel category)
        {
            if (ModelState.IsValid)
            {
                category.categoryInfo.UpdateAt = DateTime.Now;
                category.categoryInfo.UpdateBy = User.Identity.Name;
                db.Entry(category.categoryInfo).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AceAdmin/Areas/Admin/Views/Categories/Create.cshtml
@model AceAdmin.Areas.Admin.Models.CategoriesViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm mới chuyên mục</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Chuyên mục cha</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryInfo.ParentId, (SelectList)ViewBag.CategoryId, "---Chuyên mục cha---", new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.categoryInfo.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Tên chuyên mục</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Linh liên kết</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Là Menu</label>
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.isMenu)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Trạng thái</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryInfo.Status, (SelectList)ViewBag.Status, new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.categoryInfo.Status, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info btn-sm" />
                &nbsp;&nbsp;
                @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-info btn-sm" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AceAdmin/Areas/Admin/Views/Categories/Delete.cshtml
@model AceModel.Entity.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AceAdmin/Areas/Admin/Views/Categories/Details.cshtml
@model AceModel.Entity.Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Chuyên mục</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên chuyên mục
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Linh liên kết
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            Menu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            Trạng thái
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            Chuyên mục cha
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>

        <dt>
            Người tạo
            @*@Html.DisplayNameFor(model => model.CreateBy)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateBy)
        </dd>

        <dt>
            Ngày tạo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateAt)
        </dd>

        <dt>
            Cập nhật bởi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateBy)
        </dd>

        <dt>
            Ngày cập nhật
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-info btn-sm" }) &nbsp;&nbsp;
    @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-info btn-sm" })
</p>

AceAdmin/Areas/Admin/Views/Categories/Edit.cshtml
@model AceAdmin.Areas.Admin.Models.CategoriesViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Chuyên mục</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.categoryInfo.Id)

        <div class="form-group">
            <label class="control-label col-md-2" for="Name">Tên chuyên mục</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="URL">Linh liên kết</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Type">Menu</label>
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.isMenu)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Status">Trạng thái</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryInfo.Status, (SelectList)ViewBag.Status, new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.categoryInfo.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ParentId">Chuyên mục cha</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryInfo.ParentId, (SelectList)ViewBag.CategoryId, "---Chuyên mục cha---", new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.categoryInfo.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info btn-sm" />
                &nbsp;&nbsp;
                @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-info btn-sm" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AceAdmin/Areas/Admin/Views/Categories/Index.cshtml
@model IEnumerable<AceAdmin.Areas.Admin.Models.CategoriesViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<p style="margin-top: 10px;">
    @Html.ActionLink("Thêm mới", "Create", "Categories", null, new { @class = "btn btn-info btn-sm" })
</p>
<table class="wapperpager table table-bordered table-hover dataTable" id="dynamic-table">
    <thead>
        <tr>
            <th>
                Tên chuyên mục
            </th>
            <th>
                Linh liên kết
            </th>
            <th>
                Menu
            </th>
            <th>
                Trạng thái
            </th>
            <th>
                Chuyên mục cha
            </th>
            <th>
                Người tạo
            </th>
            <th>
                Ngày tạo
            </th>
            <th>
                Ngày cập nhật
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.categoryInfo.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.categoryInfo.URL)
                </td>
                <td>
                    @item.isMenu.ToString()
                </td>
                <td>
                    @*@Utitlitys.StatusToString(item.categoryInfo.Status.Value)*@
                </td>
                <td>
                    @*@controller.getCategory(item.ParentId.Value).Name*@
                    @if (item.parentCategory == null)
                    {
                        <span> --- </span>
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.parentCategory.Name)
                    }

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.categoryInfo.CreateBy)
                </td>
                <td>
                    @item.categoryInfo.CreateAt
                </td>
                <td>
                    @item.categoryInfo.UpdateAt
                </td>
                <td style="white-space:nowrap">
                    <a href='@Url.Action("Edit", "Categories", new { id = item.categoryInfo.Id })'><img src="~/Images/icons/page_white_edit.png" title="Cập nhật" /></a> |
                    <a href='@Url.Action("Delete", "Categories",new { id = item.categoryInfo.Id })'><img src="~/Images/icons/bin_closed.png" title="Xóa thông tin" /></a>
                </td>
            </tr>
        }
    </tbody>
</table>

<link rel="stylesheet" href="~/assets/css/jquery-ui.custom.min.css" />
<link rel="stylesheet" href="~/assets/css/datepicker.min.css" />
<link rel="stylesheet" href="~/assets/css/bootstrap-timepicker.min.css" />
<link rel="stylesheet" href="~/assets/css/bootstrap-datetimepicker.min.css" />
<script src="~/assets/js/jquery-ui.custom.min.js"></script>
<script src="~/assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="~/assets/js/chosen.jquery.min.js"></script>
<script src="~/assets/js/fuelux.spinner.min.js"></script>

<script src="~/assets/js/bootstrap-datepicker.min.js"></script>
<script src="~/assets/js/bootstrap-timepicker.min.js"></script>
<script src="~/assets/js/moment.min.js"></script>
<script src="~/assets/js/daterangepicker.min.js"></script>
<script src="~/assets/js/bootstrap-datetimepicker.min.js"></script>
<script src="~/assets/js/bootstrap-colorpicker.min.js"></script>
<script src="~/assets/js/jquery.knob.min.js"></script>
<script src="~/assets/js/jquery.autosize.min.js"></script>
<script src="~/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
<script src="~/assets/js/jquery.maskedinput.min.js"></script>
<script src="~/assets/js/bootstrap-tag.min.js"></script>
<script type="text/javascript">
    jQuery(function ($) {
        $.mask.definitions['~'] = '[+-]';
        $('.input-mask-phone').mask('(999) 999-9999');
        $('.input-mask-date').mask('99/99/9999');
        $('.input-mask-phone').mask('(999) 999-9999');
    });

    $('.date-picker').datepicker({
        format: 'dd-mm-yyyy',
        autoclose: true,
        todayHighlight: true
    }).next().on(ace.click_event, function () {
        $(this).prev().focus();
    });
    //show datepicker when clicking on the icon
</script>
<script type="text/javascript">
    jQuery(function ($) {
        //initiate dataTables plugin
        var oTable1 =
        $('#dynamic-table')
        .dataTable({
            bAutoWidth: false,
            "aoColumns": [
              { "bSortable": false },
              null,null, null, null, null, null, null,
              { "bSortable": false }
            ],
            "aaSorting": [],
            "pageLength": 100
        });
        //oTable1.fnAdjustColumnSizing();

        //TableTools settings
        TableTools.classes.container = "btn-group btn-overlap";
        TableTools.classes.print = {
            "body": "DTTT_Print",
            "info": "tableTools-alert gritter-item-wrapper gritter-info gritter-center white",
            "message": "tableTools-print-navbar"
        }

        //initiate TableTools extension
        var tableTools_obj = new $.fn.dataTable.TableTools(oTable1, {
            "sSwfPath": "assets/swf/copy_csv_xls_pdf.swf",

            "sRowSelector": "td:not(:last-child)",
            "sRowSelect": "multi",
            "fnRowSelected": function (row) {
                //check checkbox when row is selected
                try { $(row).find('input[type=checkbox]').get(0).checked = true }
                catch (e) { }
            },
            "fnRowDeselected": function (row) {
                //uncheck checkbox
                try { $(row).find('input[type=checkbox]').get(0).checked = false }
                catch (e) { }
            },
        });
        $(tableTools_obj.fnContainer()).appendTo($('.tableTools-container'));

        setTimeout(function () {
            $(tableTools_obj.fnContainer()).find('a.DTTT_button').each(function () {
                var div = $(this).find('> div');
                if (div.length > 0) div.tooltip({ container: 'body' });
                else $(this).tooltip({ container: 'body' });
            });
        }, 200);

        //ColVis extension
        var colvis = new $.fn.dataTable.ColVis(oTable1, {
            "buttonText": "<i class='fa fa-search'></i>",
            "aiExclude": [0, 6],
            "bShowAll": true,
            //"bRestore": true,
            "sAlign": "right",
            "fnLabel": function (i, title, th) {
                return $(th).text();//remove icons, etc
            }
        });

        //style it
        $(colvis.button()).addClass('btn-group').find('button').addClass('btn btn-white btn-info btn-bold')

        //and append it to our table tools btn-group, also add tooltip
        $(colvis.button())
        .prependTo('.tableTools-container .btn-group')
        .attr('title', 'Show/hide columns').tooltip({ container: 'body' });

        //and make the list, buttons and checkboxed Ace-like
        $(colvis.dom.collection)
        .addClass('dropdown-menu dropdown-light dropdown-caret dropdown-caret-right')
        .find('li').wrapInner('<a href="javascript:void(0)" />') //'A' tag is required for better styling
        .find('input[type=checkbox]').addClass('ace').next().addClass('lbl padding-8');

        //table checkboxes
        $('th input[type=checkbox], td input[type=checkbox]').prop('checked', false);

        //select/deselect all rows according to table header checkbox
        $('#dynamic-table > thead > tr > th input[type=checkbox]').eq(0).on('click', function () {
            var th_checked = this.checked;//checkbox inside "TH" table header

            $(this).closest('table').find('tbody > tr').each(function () {
                var row = this;
                if (th_checked) tableTools_obj.fnSelect(row);
                else tableTools_obj.fnDeselect(row);
            });
        });

        //select/deselect a row when the checkbox is checked/unchecked
        $('#dynamic-table').on('click', 'td input[type=checkbox]', function () {
            var row = $(this).closest('tr').get(0);
            if (!this.checked) tableTools_obj.fnSelect(row);
            else tableTools_obj.fnDeselect($(this).closest('tr').get(0));
        });

        $(document).on('click', '#dynamic-table .dropdown-toggle', function (e) {
            e.stopImmediatePropagation();
            e.stopPropagation();
            e.preventDefault();
        });

        //And for the first simple table, which doesn't have TableTools or dataTables
        //select/deselect all rows according to table header checkbox
        var active_class = 'active';
        $('#dynamic-table > thead > tr > th input[type=checkbox]').eq(0).on('click', function () {
            var th_checked = this.checked;//checkbox inside "TH" table header

            $(this).closest('table').find('tbody > tr').each(function () {
                var row = this;
                if (th_checked) $(row).addClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', true);
                else $(row).removeClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', false);
            });
        });

        //select/deselect a row when the checkbox is checked/unchecked
        $('#dynamic-table').on('click', 'td input[type=checkbox]', function () {
            var $row = $(this).closest('tr');
            if (this.checked) $row.addClass(active_class);
            else $row.removeClass(active_class);
        });

        /********************************/
        //add tooltip for small view action buttons in dropdown menu
        $('[data-rel="tooltip"]').tooltip({ placement: tooltip_placement });

        //tooltip placement on right or left
        function tooltip_placement(context, source) {
            var $source = $(source);
            var $parent = $source.closest('table')
            var off1 = $parent.offset();
            var w1 = $parent.width();

            var off2 = $source.offset();
            //var w2 = $source.width();

            if (parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2)) return 'right';
            return 'left';
        }

    })
</script>